---
0title: "CaseStudy_Datapreparation"
author: "Jennifer Schlindwein"
date: "12 1 2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(ggplot2)
library(tidyr)
```
Case Study
```{r,include=FALSE}
air_quality_Nov2017 <-fread('data/air_quality_Nov2017.csv',stringsAsFactors = TRUE)
air_stations_Nov2017 <-fread('data/air_stations_Nov2017.csv',stringsAsFactors = TRUE)
airquality <- merge(air_quality_Nov2017,air_stations_Nov2017,by=c("Longitude","Latitude","Station"))

airquality <-  separate(airquality,col='Generated',into=c('Day','Month','Year','Hour_date','Minute'))

airquality_o3 <- data.table(airquality)
airquality_o3[,c("NO2 Hour","NO2 Quality","NO2 Value","PM10 Hour","PM10 Quality","PM10 Value"):=NULL]
airquality_o3$Gas <- rep('O3',nrow(airquality_o3))
airquality_o3 <- setnames(airquality_o3,c("O3 Hour","O3 Quality","O3 Value"),c("Hour","Quality","Value"))
#
airquality_NO2 <- data.table(airquality)
airquality_NO2[,c("O3 Hour","O3 Quality","O3 Value","PM10 Hour","PM10 Quality","PM10 Value"):=NULL]
airquality_NO2$Gas <- rep('NO2',nrow(airquality_NO2))
airquality_NO2 <- setnames(airquality_NO2,c("NO2 Hour","NO2 Quality","NO2 Value"),c("Hour","Quality","Value"))

airquality_PM10 <- data.table(airquality)
airquality_PM10[,c("NO2 Hour","NO2 Quality","NO2 Value","O3 Hour","O3 Quality","O3 Value"):=NULL]
airquality_PM10$Gas <- rep('PM10',nrow(airquality_PM10))
airquality_PM10 <- setnames(airquality_PM10,c("PM10 Hour","PM10 Quality","PM10 Value"),c("Hour","Quality","Value"))

airquality <- rbind(airquality_NO2,airquality_o3,airquality_PM10)
airquality[,c("Air Quality","Hour_date","Date Time","Ubication","Quality","Minute" ):=NULL]
airquality$Hour <- as.numeric(gsub("h", "",airquality$Hour))

qualitat_aire_contaminants_pollutants <- fread('external_data/qualitat_aire_contaminants_pollutants.csv',stringsAsFactors = TRUE)
qualitat_aire_contaminants_pollutants <-qualitat_aire_contaminants_pollutants[Desc_Contaminant %in% c('NO2','O3','PM10'),]
qualitat_aire_contaminants_pollutants <- setnames(qualitat_aire_contaminants_pollutants,'Desc_Contaminant','Gas')

qualitat_aire_estacions_bcn_2021 <- fread('external_data/measurement_stations/2021_qualitat_aire_estacions.csv',stringsAsFactors = TRUE)

for (filename in list.files('external_data/2019')){
  dt <- fread(paste('external_data/2019/',filename,sep=''))
  dt <- merge(dt,qualitat_aire_contaminants_pollutants,by.x='CODI_CONTAMINANT',by.y='Codi_Contaminant')
  dt <- merge(dt,qualitat_aire_estacions_bcn_2021,by.x=c('ESTACIO','CODI_CONTAMINANT'),by.y=c('Estacio','Codi_Contaminant'))
  dt <- melt(dt,measure.vars = c("H01","H02","H03","H04","H05","H06","H07","H08","H09","H10","H11","H12","H13","H14","H15","H16","H17","H18","H19","H20","H21","H22","H23","H24"),variable.name='Hour',value.name='Value')
  dt <- setnames(dt,c("Longitud","Latitud","nom_cabina","DIA","MES","ANY","Nom_districte","Nom_barri"),c("Longitude","Latitude","Station","Day","Month","Year","District Name"   ,"Neighborhood Name"))
  dt$Hour <- as.numeric(gsub("H", "", dt$Hour))
  dt <-dt[,c("Longitude","Latitude","Station","Hour","Value","Day","Month","Year","District Name"  ,"Neighborhood Name","Gas")]
  airquality <- rbind(airquality,dt)
}
rm(list=setdiff(ls(), "airquality"))
```


